/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    { pattern: /bg-folder-(documents|projects|photos|videos|music|work|downloads|personal)/ },
    { pattern: /text-folder-(documents|projects|photos|videos|music|work|downloads|personal)/ },
    { pattern: /border-folder-(documents|projects|photos|videos|music|work|downloads|personal)/ },
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "bg-canvas": "#F7F5F0",
        "secondary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "on-error": "#ffffff",
        "outline": "#737686",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "primary-fixed": "#dbe1ff",
        "on-surface-variant": "#434655",
        "on-tertiary-container": "#ffede6",
        "folder-projects": "#8B5CF6",
        "on-background": "#1c1b1b",
        "surface-hover": "#ECEAE5",
        "background": "#fcf9f8",
        "error-container": "#ffdad6",
        "folder-videos": "#F97316",
        "surface-selected": "#E5E1D8",
        "surface-primary": "#FFFFFF",
        "inverse-primary": "#b4c5ff",
        "folder-downloads": "#64748B",
        "text-muted": "#777777",
        "on-secondary-fixed": "#00174b",
        "on-primary": "#ffffff",
        "border-base": "#DDD9D0",
        "surface-secondary": "#F1EFEA",
        "on-tertiary-fixed": "#360f00",
        "inverse-on-surface": "#f3f0ef",
        "folder-personal": "#EC4899",
        "tertiary-container": "#bc4800",
        "surface-container": "#f0edec",
        "on-secondary-container": "#394c84",
        "folder-music": "#10B981",
        "folder-documents": "#2563EB",
        "on-primary-container": "#eeefff",
        "surface-variant": "#e5e2e1",
        "text-secondary": "#555555",
        "on-error-container": "#93000a",
        "folder-work": "#0D9488",
        "secondary-container": "#acbfff",
        "surface-container-low": "#f6f3f2",
        "surface-container-high": "#ebe7e7",
        "outline-variant": "#c3c6d7",
        "surface-container-highest": "#e5e2e1",
        "surface-bright": "#fcf9f8",
        "on-surface": "#1c1b1b",
        "tertiary": "#943700",
        "on-primary-fixed-variant": "#003ea8",
        "surface-tint": "#0053db",
        "secondary": "#495c95",
        "tertiary-fixed-dim": "#ffb596",
        "folder-photos": "#F59E0B",
        "inverse-surface": "#313030",
        "primary": "#004ac6",
        "tertiary-fixed": "#ffdbcd",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface": "#fcf9f8",
        "primary-fixed-dim": "#b4c5ff",
        "primary-container": "#2563eb",
        "surface-container-lowest": "#ffffff",
        "text-primary": "#111111",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#31447b",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dcd9d9"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "space-xs": "0.25rem",
        "space-xl": "2rem",
        "margin": "1.5rem",
        "gutter": "1rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-sm": "0.5rem"
      },
      "fontFamily": {
        "headline-md": ["Montserrat"],
        "body-sm": ["Montserrat"],
        "body-lg": ["Montserrat"],
        "headline-lg": ["Montserrat"],
        "display": ["Montserrat"],
        "headline-sm": ["Montserrat"],
        "body-md": ["Montserrat"],
        "label-md": ["Montserrat"],
        "label-lg": ["Montserrat"],
        "label-sm": ["Montserrat"]
      },
      "fontSize": {
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.015em", "fontWeight": "600" }],
        "display": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
        "label-lg": ["14px", { "lineHeight": "20px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.02em", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
